/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { DeviceLabels, deviceLabelsSchema } from '../deviceLabels';

/** This is a container type for any-of types. */
export type LabelsListDeviceIds = DeviceLabels;

export const labelsListDeviceIdsSchema: Schema<LabelsListDeviceIds> = anyOf([
  deviceLabelsSchema,
]);

export namespace LabelsListDeviceIds {
  /**
   * Validation method to narrow down union type to DeviceLabels type case.
   *
   * This is DeviceLabels case.
   */
  export function isDeviceLabels(value: unknown): value is DeviceLabels {
    const validationResult = validateAndMap(value, deviceLabelsSchema);
    return validationResult.errors === false;
  }
}
