/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import { Addressquery, addressquerySchema } from '../addressquery';
import {
  Customernamequery,
  customernamequerySchema,
} from '../customernamequery';

/** This is a container type for any-of types. */
export type ProfileRequestPrimaryPlaceOfUse = Customernamequery | Addressquery;

export const profileRequestPrimaryPlaceOfUseSchema: Schema<ProfileRequestPrimaryPlaceOfUse> = anyOf(
  [customernamequerySchema, addressquerySchema]
);

export namespace ProfileRequestPrimaryPlaceOfUse {
  /**
   * Validation method to narrow down union type to Customernamequery type case.
   *
   * This is customernamequery case.
   */
  export function isCustomernamequery(
    value: unknown
  ): value is Customernamequery {
    const validationResult = validateAndMap(value, customernamequerySchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to Addressquery type case.
   *
   * This is addressquery case.
   */
  export function isAddressquery(value: unknown): value is Addressquery {
    const validationResult = validateAndMap(value, addressquerySchema);
    return validationResult.errors === false;
  }
}
