/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  logOutRequestSchema,
  type LogOutRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { sessionManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface EndConnectivityManagementSessionMCPToolRequest {
}

const endConnectivityManagementSessionMCPToolRequestSchema = object({  });

async function handleEndConnectivityManagementSession(
  args: unknown | EndConnectivityManagementSessionMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, endConnectivityManagementSessionMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await sessionManagementController.endConnectivityManagementSession();
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function sessionManagementEndConnectivityManagementSessionTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "sessionManagement-endConnectivityManagementSession",
      description: `Ends a Connectivity Management session.`,
      inputSchema: await schemas.loadSchema("Session Management", "EndConnectivityManagementSession"),
    },
    handler: handleEndConnectivityManagementSession,
  };
}

