/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  sessionResetPasswordRequestSchema,
  sessionResetPasswordResultSchema,
  type SessionResetPasswordResult,
  type SessionResetPasswordRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { sessionManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ResetConnectivityManagementPasswordMCPToolRequest {
  'body': SessionResetPasswordRequest,
}

const resetConnectivityManagementPasswordMCPToolRequestSchema = object({
  body: ['body', lazy(() => sessionResetPasswordRequestSchema)],
});

async function handleResetConnectivityManagementPassword(
  args: unknown | ResetConnectivityManagementPasswordMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, resetConnectivityManagementPasswordMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await sessionManagementController.resetConnectivityManagementPassword(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function sessionManagementResetConnectivityManagementPasswordTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "sessionManagement-resetConnectivityManagementPassword",
      description: `The new password is effective immediately. Passwords do not expire, but Verizon recommends changing your password every 90 days.`,
      inputSchema: await schemas.loadSchema("Session Management", "ResetConnectivityManagementPassword"),
    },
    handler: handleResetConnectivityManagementPassword,
  };
}

