/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  object,
  optional,
  string,
  validateAndMap,
} from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  logInRequestSchema,
  logInResultSchema,
  type LogInResult,
  type LogInRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { sessionManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface StartConnectivityManagementSessionMCPToolRequest {
  'body': LogInRequest,
}

const startConnectivityManagementSessionMCPToolRequestSchema = object({
  body: ['body', optional(lazy(() => logInRequestSchema))],
});

async function handleStartConnectivityManagementSession(
  args: unknown | StartConnectivityManagementSessionMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, startConnectivityManagementSessionMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await sessionManagementController.startConnectivityManagementSession(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function sessionManagementStartConnectivityManagementSessionTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "sessionManagement-startConnectivityManagementSession",
      description: `Initiates a Connectivity Management session and returns a VZ-M2M session token that is required in subsequent API requests.`,
      inputSchema: await schemas.loadSchema("Session Management", "StartConnectivityManagementSession"),
    },
    handler: handleStartConnectivityManagementSession,
  };
}

