/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  connectivityManagementSuccessResultSchema,
  createDeviceGroupRequestSchema,
  type ConnectivityManagementSuccessResult,
  type CreateDeviceGroupRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceGroupsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface CreateDeviceGroupMCPToolRequest {
  'body': CreateDeviceGroupRequest,
}

const createDeviceGroupMCPToolRequestSchema = object({
  body: ['body', lazy(() => createDeviceGroupRequestSchema)],
});

async function handleCreateDeviceGroup(
  args: unknown | CreateDeviceGroupMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, createDeviceGroupMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceGroupsController.createDeviceGroup(mappingResult.result['body']);
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceGroupsCreateDeviceGroupTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceGroups-createDeviceGroup",
      description: `Create a new device group and optionally add devices to the group. Device groups can make it easier to manage similar devices and to get reports on their usage.`,
      inputSchema: await schemas.loadSchema("Device Groups", "CreateDeviceGroup"),
    },
    handler: handleCreateDeviceGroup,
  };
}

