/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  connectivityManagementSuccessResultSchema,
  deviceGroupUpdateRequestSchema,
  type ConnectivityManagementSuccessResult,
  type DeviceGroupUpdateRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceGroupsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UpdateDeviceGroupMCPToolRequest {
  'aname': string,
  'gname': string,
  'body': DeviceGroupUpdateRequest,
}

const updateDeviceGroupMCPToolRequestSchema = object({
  aname: ['aname', string()],
  gname: ['gname', string()],
  body: ['body', lazy(() => deviceGroupUpdateRequestSchema)],
});

async function handleUpdateDeviceGroup(
  args: unknown | UpdateDeviceGroupMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, updateDeviceGroupMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceGroupsController.updateDeviceGroup(
      mappingResult.result['aname'],
      mappingResult.result['gname'],
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceGroupsUpdateDeviceGroupTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceGroups-updateDeviceGroup",
      description: `Make changes to a device group, including changing the name and description, and adding or removing devices.`,
      inputSchema: await schemas.loadSchema("Device Groups", "UpdateDeviceGroup"),
    },
    handler: handleUpdateDeviceGroup,
  };
}

