/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { accountSchema, type Account } from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { accountsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetAccountInformationMCPToolRequest {
  'aname': string,
}

const getAccountInformationMCPToolRequestSchema = object({
  aname: ['aname', string()],
});

async function handleGetAccountInformation(
  args: unknown | GetAccountInformationMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, getAccountInformationMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await accountsController.getAccountInformation(mappingResult.result['aname']);
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function accountsGetAccountInformationTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "accounts-getAccountInformation",
      description: `Returns information about a specified account.`,
      inputSchema: await schemas.loadSchema("Accounts", "GetAccountInformation"),
    },
    handler: handleGetAccountInformation,
  };
}

