/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  accountStatesAndServicesSchema,
  type AccountStatesAndServices,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { accountsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListAccountStatesAndServicesMCPToolRequest {
  'aname': string,
}

const listAccountStatesAndServicesMCPToolRequestSchema = object({
  aname: ['aname', string()],
});

async function handleListAccountStatesAndServices(
  args: unknown | ListAccountStatesAndServicesMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listAccountStatesAndServicesMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await accountsController.listAccountStatesAndServices(
      mappingResult.result['aname']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function accountsListAccountStatesAndServicesTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "accounts-listAccountStatesAndServices",
      description: `Returns a list and details of all custom services and states defined for a specified account.`,
      inputSchema: await schemas.loadSchema("Accounts", "ListAccountStatesAndServices"),
    },
    handler: handleListAccountStatesAndServices,
  };
}

