/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  AccountRequestsController,
  AsynchronousRequestResult,
  RequestStatusEnum,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('AccountRequestsController', () => {
  let controller : AccountRequestsController;

  beforeAll(() => {
    controller = new AccountRequestsController(testClient);
  });

  it('should Test GetCurrentAsynchronousRequestStatus', async () => {
    const aname = '0252012345-00001';

    const requestId = '86c83330-4bf5-4235-9c4e-a83f93aeae4c';

    const response = await makeApiCall(
      () => controller.getCurrentAsynchronousRequestStatus(aname, requestId)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: AsynchronousRequestResult = {
      requestId: '86c83330-4bf5-4235-9c4e-a83f93aeae4c',
      status: RequestStatusEnum.Success,
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
