/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  ActivateDeviceProfileRequest,
  DeviceProfileManagementController,
} from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('DeviceProfileManagementController', () => {
  let controller : DeviceProfileManagementController;

  beforeAll(() => {
    controller = new DeviceProfileManagementController(testClient);
  });

  it('should Test ActivateDeviceThroughProfile', async () => {
    const body: ActivateDeviceProfileRequest = {
      devices: [
        {
          deviceIds: [
            {
              id: '32-digit EID',
              kind: 'eid',
            },
            {
              id: '15-digit IMEI',
              kind: 'imei',
            }
          ],
        }
      ],
      accountName: '0000123456-00001',
      servicePlan: 'The service plan name',
      mdnZipCode: 'five digit zip code',
    };

    const response = await makeApiCall(
      () => controller.activateDeviceThroughProfile(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
