/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  DeviceDiagnosticsController,
  DeviceManagementResult,
  RetrieveMonitorsRequest,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('DeviceDiagnosticsController', () => {
  let controller : DeviceDiagnosticsController;

  beforeAll(() => {
    controller = new DeviceDiagnosticsController(testClient);
  });

  it('should Test RetrieveActiveMonitorsUsingPOST', async () => {
    const body: RetrieveMonitorsRequest = {
      accountName: '0242123520-00001',
      devices: [
        {
          deviceIds: [
            {
              id: '12016560696',
              kind: 'msisdn',
            }
          ],
        }
      ],
    };

    const response = await makeApiCall(
      () => controller.retrieveActiveMonitorsUsingPOST(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: DeviceManagementResult = {
      requestId: '595f5c44-c31c-4552-8670-020a1545a84d',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
