/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  DeviceManagementResult,
  EUICCDeviceProfileManagementController,
  ProfileChangeStateRequest,
} from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('EUICCDeviceProfileManagementController', () => {
  let controller : EUICCDeviceProfileManagementController;

  beforeAll(() => {
    controller = new EUICCDeviceProfileManagementController(testClient);
  });

  it('should Test DownloadLocalProfileToEnable', async () => {
    const body: ProfileChangeStateRequest = {
      devices: [
        {
          deviceIds: [
            {
              id: '678912789123453456784008666456',
              kind: 'eid',
            },
            {
              id: '78425989148000000840',
              kind: 'iccid',
            }
          ],
        }
      ],
      accountName: '1223334444-00001',
      smsrOid: '1.3.6.1.4.1.31746.1.500.200.101.5',
    };

    const response = await makeApiCall(
      () => controller.downloadLocalProfileToEnable(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: DeviceManagementResult = {
      requestId: '595f5c44-c31c-4552-8670-020a1545a84d',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test DownloadLocalProfileToDisable', async () => {
    const body: ProfileChangeStateRequest = {
      devices: [
        {
          deviceIds: [
            {
              id: '678912789123453456784008666456',
              kind: 'eid',
            },
            {
              id: '78425989148000000840',
              kind: 'iccid',
            }
          ],
        }
      ],
      accountName: '1223334444-00001',
      smsrOid: '1.3.6.1.4.1.31746.1.500.200.101.5',
    };

    const response = await makeApiCall(
      () => controller.downloadLocalProfileToDisable(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: DeviceManagementResult = {
      requestId: '595f5c44-c31c-4552-8670-020a1545a84d',
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test EnableLocalProfile', async () => {
    const body: ProfileChangeStateRequest = {
      devices: [
        {
          deviceIds: [
            {
              id: '678912789123453456784008666456',
              kind: 'eid',
            },
            {
              id: '78425989148000000840',
              kind: 'iccid',
            }
          ],
        }
      ],
      accountName: '1223334444-00001',
      smsrOid: '1.3.6.1.4.1.31746.1.500.200.101.5',
    };

    const response = await makeApiCall(
      () => controller.enableLocalProfile(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test DisableLocalProfile', async () => {
    const body: ProfileChangeStateRequest = {
      devices: [
        {
          deviceIds: [
            {
              id: '678912789123453456784008666456',
              kind: 'eid',
            },
            {
              id: '78425989148000000840',
              kind: 'iccid',
            }
          ],
        }
      ],
      accountName: '1223334444-00001',
      smsrOid: '1.3.6.1.4.1.31746.1.500.200.101.5',
    };

    const response = await makeApiCall(
      () => controller.disableLocalProfile(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test DeleteLocalProfile', async () => {
    const body: ProfileChangeStateRequest = {
      devices: [
        {
          deviceIds: [
            {
              id: '678912789123453456784008666456',
              kind: 'eid',
            },
            {
              id: '78425989148000000840',
              kind: 'iccid',
            }
          ],
        }
      ],
      accountName: '1223334444-00001',
      smsrOid: '1.3.6.1.4.1.31746.1.500.200.101.5',
    };

    const response = await makeApiCall(
      () => controller.deleteLocalProfile(body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
