/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ServicePlan, ServicePlansController } from '../src';
import { testClient } from './testClient';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper';

describe('ServicePlansController', () => {
  let controller : ServicePlansController;

  beforeAll(() => {
    controller = new ServicePlansController(testClient);
  });

  it('should Test ListAccountServicePlans', async () => {
    const aname = '0252012345-00001';

    const response = await makeApiCall(
      () => controller.listAccountServicePlans(aname)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: ServicePlan[] = [
      {
        carrierServicePlanCode: '84638',
        code: 'M2MSHR5GB',
        name: '2MSHR5GB',
        sizeKb: BigInt(0),
      },
      {
        carrierServicePlanCode: '74644',
        code: 'NTL200TALK',
        name: 'TNTL200TALK',
        sizeKb: BigInt(0),
      }
    ];

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
