/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  billedusageListRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type BilledusageListRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface BilledUsageInfoMCPToolRequest {
  'body': BilledusageListRequest,
}

const billedUsageInfoMCPToolRequestSchema = object({
  body: ['body', lazy(() => billedusageListRequestSchema)],
});

async function handleBilledUsageInfo(
  args: unknown | BilledUsageInfoMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, billedUsageInfoMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.billedUsageInfo(mappingResult.result['body']);
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementBilledUsageInfoTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-billedUsageInfo",
      description: `Gets billed usage for for either multiple devices or an entire billing account.`,
      inputSchema: await schemas.loadSchema("Device Management", "BilledUsageInfo"),
    },
    handler: handleBilledUsageInfo,
  };
}

