/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceMismatchListRequestSchema,
  deviceMismatchListResultSchema,
  type DeviceMismatchListResult,
  type DeviceMismatchListRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListDevicesWithImeiIccidMismatchMCPToolRequest {
  'body': DeviceMismatchListRequest,
}

const listDevicesWithImeiIccidMismatchMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceMismatchListRequestSchema)],
});

async function handleListDevicesWithImeiIccidMismatch(
  args: unknown | ListDevicesWithImeiIccidMismatchMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listDevicesWithImeiIccidMismatchMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.listDevicesWithImeiIccidMismatch(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementListDevicesWithImeiIccidMismatchTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-listDevicesWithImeiIccidMismatch",
      description: `Returns a list of all 4G devices with an ICCID (SIM) that was not activated with the expected IMEI (hardware) during a specified time frame.`,
      inputSchema: await schemas.loadSchema("Device Management", "ListDevicesWithImeiIccidMismatch"),
    },
    handler: handleListDevicesWithImeiIccidMismatch,
  };
}

