/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceProvisioningHistoryListRequestSchema,
  deviceProvisioningHistoryListResultSchema,
  type DeviceProvisioningHistoryListResult,
  type DeviceProvisioningHistoryListRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListDevicesProvisioningHistoryMCPToolRequest {
  'body': DeviceProvisioningHistoryListRequest,
}

const listDevicesProvisioningHistoryMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceProvisioningHistoryListRequestSchema)],
});

async function handleListDevicesProvisioningHistory(
  args: unknown | ListDevicesProvisioningHistoryMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listDevicesProvisioningHistoryMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.listDevicesProvisioningHistory(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementListDevicesProvisioningHistoryTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-listDevicesProvisioningHistory",
      description: `Returns the provisioning history of a specified device during a specified time period.`,
      inputSchema: await schemas.loadSchema("Device Management", "ListDevicesProvisioningHistory"),
    },
    handler: handleListDevicesProvisioningHistory,
  };
}

