/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  carrierActionsRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type CarrierActionsRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface RestoreServiceForSuspendedDevicesMCPToolRequest {
  'body': CarrierActionsRequest,
}

const restoreServiceForSuspendedDevicesMCPToolRequestSchema = object({
  body: ['body', lazy(() => carrierActionsRequestSchema)],
});

async function handleRestoreServiceForSuspendedDevices(
  args: unknown | RestoreServiceForSuspendedDevicesMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, restoreServiceForSuspendedDevicesMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.restoreServiceForSuspendedDevices(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementRestoreServiceForSuspendedDevicesTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-restoreServiceForSuspendedDevices",
      description: `Restores service to one or more suspended devices.`,
      inputSchema: await schemas.loadSchema("Device Management", "RestoreServiceForSuspendedDevices"),
    },
    handler: handleRestoreServiceForSuspendedDevices,
  };
}

