/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  contactInfoUpdateRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type ContactInfoUpdateRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UpdateDevicesContactInformationMCPToolRequest {
  'body': ContactInfoUpdateRequest,
}

const updateDevicesContactInformationMCPToolRequestSchema = object({
  body: ['body', lazy(() => contactInfoUpdateRequestSchema)],
});

async function handleUpdateDevicesContactInformation(
  args: unknown | UpdateDevicesContactInformationMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, updateDevicesContactInformationMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.updateDevicesContactInformation(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUpdateDevicesContactInformationTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-updateDevicesContactInformation",
      description: `Sends a CarrierService callback message for each device in the request when the contact information has been changed, or if there was a problem and the change could not be completed.`,
      inputSchema: await schemas.loadSchema("Device Management", "UpdateDevicesContactInformation"),
    },
    handler: handleUpdateDevicesContactInformation,
  };
}

