/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  labelsListSchema,
  type DeviceManagementResult,
  type LabelsList,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UsageSegmentationLabelDeletionMCPToolRequest {
  'accountName': string,
  'LabelList': LabelsList,
}

const usageSegmentationLabelDeletionMCPToolRequestSchema = object({
  accountName: ['accountName', string()],
  labelList: ['LabelList', lazy(() => labelsListSchema)],
});

async function handleUsageSegmentationLabelDeletion(
  args: unknown | UsageSegmentationLabelDeletionMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, usageSegmentationLabelDeletionMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.usageSegmentationLabelDeletion(
      mappingResult.result['accountName'],
      mappingResult.result['labelList']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUsageSegmentationLabelDeletionTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-usageSegmentationLabelDeletion",
      description: `Allow customers to remove the associated label from a device.`,
      inputSchema: await schemas.loadSchema("Device Management", "UsageSegmentationLabelDeletion"),
    },
    handler: handleUsageSegmentationLabelDeletion,
  };
}

