/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  requestResponseSchema,
  stopMonitorRequestSchema,
  type RequestResponse,
  type StopMonitorRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceMonitoringController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface StopDeviceReachabilityMCPToolRequest {
  'stopreachabilitypayload': StopMonitorRequest,
}

const stopDeviceReachabilityMCPToolRequestSchema = object({
  stopreachabilitypayload: [
    'stopreachabilitypayload',
    lazy(() => stopMonitorRequestSchema),
  ],
});

async function handleStopDeviceReachability(
  args: unknown | StopDeviceReachabilityMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, stopDeviceReachabilityMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceMonitoringController.stopDeviceReachability(
      mappingResult.result['stopreachabilitypayload']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceMonitoringStopDeviceReachabilityTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceMonitoring-stopDeviceReachability",
      inputSchema: await schemas.loadSchema("Device Monitoring", "StopDeviceReachability"),
    },
    handler: handleStopDeviceReachability,
  };
}

