/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  notificationReportStatusRequestSchema,
  type DeviceManagementResult,
  type NotificationReportStatusRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceDiagnosticsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DeviceReachabilityStatusUsingPOSTMCPToolRequest {
  'body': NotificationReportStatusRequest,
}

const deviceReachabilityStatusUsingPOSTMCPToolRequestSchema = object({
  body: ['body', lazy(() => notificationReportStatusRequestSchema)],
});

async function handleDeviceReachabilityStatusUsingPOST(
  args: unknown | DeviceReachabilityStatusUsingPOSTMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, deviceReachabilityStatusUsingPOSTMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceDiagnosticsController.deviceReachabilityStatusUsingPOST(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceDiagnosticsDeviceReachabilityStatusUsingPOSTTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceDiagnostics-deviceReachabilityStatusUsingPOST",
      description: `If the devices do not already exist in the account, this API resource adds them before activation.`,
      inputSchema: await schemas.loadSchema("Device Diagnostics", "DeviceReachabilityStatusUsingPOST"),
    },
    handler: handleDeviceReachabilityStatusUsingPOST,
  };
}

