/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  retrieveMonitorsRequestSchema,
  type DeviceManagementResult,
  type RetrieveMonitorsRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceDiagnosticsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface RetrieveActiveMonitorsUsingPOSTMCPToolRequest {
  'body': RetrieveMonitorsRequest,
}

const retrieveActiveMonitorsUsingPOSTMCPToolRequestSchema = object({
  body: ['body', lazy(() => retrieveMonitorsRequestSchema)],
});

async function handleRetrieveActiveMonitorsUsingPOST(
  args: unknown | RetrieveActiveMonitorsUsingPOSTMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, retrieveActiveMonitorsUsingPOSTMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceDiagnosticsController.retrieveActiveMonitorsUsingPOST(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceDiagnosticsRetrieveActiveMonitorsUsingPOSTTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceDiagnostics-retrieveActiveMonitorsUsingPOST",
      description: `Retrieve all the active monitors.`,
      inputSchema: await schemas.loadSchema("Device Diagnostics", "RetrieveActiveMonitorsUsingPOST"),
    },
    handler: handleRetrieveActiveMonitorsUsingPOST,
  };
}

