/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  profileChangeStateRequestSchema,
  requestResponseSchema,
  type RequestResponse,
  type ProfileChangeStateRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { eUICCDeviceProfileManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DeleteLocalProfileMCPToolRequest {
  'body': ProfileChangeStateRequest,
}

const deleteLocalProfileMCPToolRequestSchema = object({
  body: ['body', lazy(() => profileChangeStateRequestSchema)],
});

async function handleDeleteLocalProfile(
  args: unknown | DeleteLocalProfileMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, deleteLocalProfileMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await eUICCDeviceProfileManagementController.deleteLocalProfile(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function eUICCDeviceProfileManagementDeleteLocalProfileTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "eUICCDeviceProfileManagement-deleteLocalProfile",
      description: `Delete a local profile from eUICC devices. If the local profile is enabled, it will first be disabled and the boot or default profile will be enabled.`,
      inputSchema: await schemas.loadSchema("eUICC Device Profile Management", "DeleteLocalProfile"),
    },
    handler: handleDeleteLocalProfile,
  };
}

