/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  profileChangeStateRequestSchema,
  requestResponseSchema,
  type RequestResponse,
  type ProfileChangeStateRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { eUICCDeviceProfileManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DisableLocalProfileMCPToolRequest {
  'body': ProfileChangeStateRequest,
}

const disableLocalProfileMCPToolRequestSchema = object({
  body: ['body', lazy(() => profileChangeStateRequestSchema)],
});

async function handleDisableLocalProfile(
  args: unknown | DisableLocalProfileMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, disableLocalProfileMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await eUICCDeviceProfileManagementController.disableLocalProfile(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function eUICCDeviceProfileManagementDisableLocalProfileTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "eUICCDeviceProfileManagement-disableLocalProfile",
      description: `Disable a local profile on eUICC devices. The default or boot profile will become the enabled profile.`,
      inputSchema: await schemas.loadSchema("eUICC Device Profile Management", "DisableLocalProfile"),
    },
    handler: handleDisableLocalProfile,
  };
}

