/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  asynchronousRequestResultSchema,
  type AsynchronousRequestResult,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { accountRequestsController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetCurrentAsynchronousRequestStatusMCPToolRequest {
  'aname': string,
  'requestId': string,
}

const getCurrentAsynchronousRequestStatusMCPToolRequestSchema = object({
  aname: ['aname', string()],
  requestId: ['requestId', string()],
});

async function handleGetCurrentAsynchronousRequestStatus(
  args: unknown | GetCurrentAsynchronousRequestStatusMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, getCurrentAsynchronousRequestStatusMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await accountRequestsController.getCurrentAsynchronousRequestStatus(
      mappingResult.result['aname'],
      mappingResult.result['requestId']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function accountRequestsGetCurrentAsynchronousRequestStatusTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "accountRequests-getCurrentAsynchronousRequestStatus",
      description: `Returns the current status of an asynchronous request that was made for a single device.`,
      inputSchema: await schemas.loadSchema("Account Requests", "GetCurrentAsynchronousRequestStatus"),
    },
    handler: handleGetCurrentAsynchronousRequestStatus,
  };
}

