/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  profileChangeStateRequestSchema,
  type DeviceManagementResult,
  type ProfileChangeStateRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { eUICCDeviceProfileManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DownloadLocalProfileToEnableMCPToolRequest {
  'body': ProfileChangeStateRequest,
}

const downloadLocalProfileToEnableMCPToolRequestSchema = object({
  body: ['body', lazy(() => profileChangeStateRequestSchema)],
});

async function handleDownloadLocalProfileToEnable(
  args: unknown | DownloadLocalProfileToEnableMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, downloadLocalProfileToEnableMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await eUICCDeviceProfileManagementController.downloadLocalProfileToEnable(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function eUICCDeviceProfileManagementDownloadLocalProfileToEnableTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "eUICCDeviceProfileManagement-downloadLocalProfileToEnable",
      description: `Downloads an eUICC local profile to devices and enables the profile.`,
      inputSchema: await schemas.loadSchema("eUICC Device Profile Management", "DownloadLocalProfileToEnable"),
    },
    handler: handleDownloadLocalProfileToEnable,
  };
}

