/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { McpError } from '@modelcontextprotocol/sdk/types.js';
import { initializeServer } from './mcp-server.js';


async function main() {
  await initializeServer();
}

// Execute main and handle top-level errors
main().catch((error) => {
  if (error && error instanceof McpError) {
    console.error(`MCP Error ${error.code}: ${error.message}`);
  } else if (error && error instanceof Error) {
    console.error("Fatal error in main():", error.message, error.stack);
  } else {
    console.error("Unexpected fatal error:", error);
  }
  process.exit(1);
});

