/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import { ApiError } from 'sdksio-verizon-apis-sdk';

export function stringifyRawJson(object: unknown): string {
  return JSON.stringify(object, (_, value: unknown) => {
    return typeof value === "bigint" ? Number(value) : value;
  });
}

export function createErrorMessage(error: unknown): CallToolResult {
  if (error instanceof ApiError) {
    const errorObj = {
      statusCode: error.statusCode,
      headers: error.headers,
      body: error.body
    };

    console.error("API Error:", errorObj);

    try {
      return wrapErrorMessage(stringifyRawJson(errorObj));
    } catch (stringifyError) {
      return wrapErrorMessage(`Tool Error: API error occurred, but details could not be serialized. Message: ${stringifyError}`);
    }
  }
  else if (error instanceof Error) {
    console.error("Unexpected Tool Error:", error.message);
    return wrapErrorMessage(`Tool Error: ${error.message}`);
  }

  console.error("Unexpected Tool Error:", stringifyRawJson(error));
  return wrapErrorMessage(`Tool Error: ${stringifyRawJson(error)}`);
}

function wrapErrorMessage(message: string): CallToolResult {
  return {
    content: [{ type: "text", text: message }],
    isError: true, // Indicate to the LLM that the tool failed
  };
}
