/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  requestResponseSchema,
  setFallbackAttributeRequestSchema,
  type RequestResponse,
  type SetFallbackAttributeRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceProfileManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ProfileToSetFallbackAttributeMCPToolRequest {
  'body': SetFallbackAttributeRequest,
}

const profileToSetFallbackAttributeMCPToolRequestSchema = object({
  body: ['body', lazy(() => setFallbackAttributeRequestSchema)],
});

async function handleProfileToSetFallbackAttribute(
  args: unknown | ProfileToSetFallbackAttributeMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, profileToSetFallbackAttributeMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceProfileManagementController.profileToSetFallbackAttribute(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceProfileManagementProfileToSetFallbackAttributeTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceProfileManagement-profileToSetFallbackAttribute",
      description: `Allows the profile to set the fallback attribute to the device.`,
      inputSchema: await schemas.loadSchema("Device Profile Management", "ProfileToSetFallbackAttribute"),
    },
    handler: handleProfileToSetFallbackAttribute,
  };
}

