/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deactivateDeviceProfileRequestSchema,
  requestResponseSchema,
  type RequestResponse,
  type DeactivateDeviceProfileRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceProfileManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ProfileToDeactivateDeviceMCPToolRequest {
  'body': DeactivateDeviceProfileRequest,
}

const profileToDeactivateDeviceMCPToolRequestSchema = object({
  body: ['body', lazy(() => deactivateDeviceProfileRequestSchema)],
});

async function handleProfileToDeactivateDevice(
  args: unknown | ProfileToDeactivateDeviceMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, profileToDeactivateDeviceMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceProfileManagementController.profileToDeactivateDevice(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceProfileManagementProfileToDeactivateDeviceTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceProfileManagement-profileToDeactivateDevice",
      description: `Uses the profile to deactivate the device.`,
      inputSchema: await schemas.loadSchema("Device Profile Management", "ProfileToDeactivateDevice"),
    },
    handler: handleProfileToDeactivateDevice,
  };
}

