/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  oAuthTokenSchema,
  type OAuthToken,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { oAuthAuthorizationController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface RequestTokenThingspaceOauthMCPToolRequest {
  'Authorization': string,
  'scope': string,
}

const requestTokenThingspaceOauthMCPToolRequestSchema = object({
  authorization: ['Authorization', string()],
  scope: ['scope', optional(string())],
});

async function handleRequestTokenThingspaceOauth(
  args: unknown | RequestTokenThingspaceOauthMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, requestTokenThingspaceOauthMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await oAuthAuthorizationController.requestTokenThingspaceOauth(
      mappingResult.result['authorization'],
      mappingResult.result['scope']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function oAuthAuthorizationRequestTokenThingspaceOauthTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "oAuthAuthorization-requestTokenThingspaceOauth",
      description: `Create a new OAuth 2 token.`,
      inputSchema: await schemas.loadSchema("OAuth Authorization", "request tokenThingspaceOauth"),
    },
    handler: handleRequestTokenThingspaceOauth,
  };
}

