/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  object,
  optional,
  string,
  validateAndMap,
} from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  sMSMessagesQueryResultSchema,
  type SMSMessagesQueryResult,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { sMSController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListDevicesSMSMessagesMCPToolRequest {
  'aname': string,
  'next': bigint,
}

const listDevicesSMSMessagesMCPToolRequestSchema = object({
  aname: ['aname', string()],
  next: ['next', optional(bigint())],
});

async function handleListDevicesSMSMessages(
  args: unknown | ListDevicesSMSMessagesMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listDevicesSMSMessagesMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await sMSController.listDevicesSMSMessages(
      mappingResult.result['aname'],
      mappingResult.result['next']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function sMSListDevicesSMSMessagesTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "sMS-listDevicesSMSMessages",
      description: `When HTTP status is 202, a URL will be returned in the Location header of the form /sms/{aname}/history?next={token}. This URL can be used to request the next set of messages.`,
      inputSchema: await schemas.loadSchema("SMS", "ListDevicesSMSMessages"),
    },
    handler: handleListDevicesSMSMessages,
  };
}

