/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  connectivityManagementSuccessResultSchema,
  type ConnectivityManagementSuccessResult,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { sMSController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface StartQueuedSMSDeliveryMCPToolRequest {
  'aname': string,
}

const startQueuedSMSDeliveryMCPToolRequestSchema = object({
  aname: ['aname', string()],
});

async function handleStartQueuedSMSDelivery(
  args: unknown | StartQueuedSMSDeliveryMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, startQueuedSMSDeliveryMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await sMSController.startQueuedSMSDelivery(mappingResult.result['aname']);
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function sMSStartQueuedSMSDeliveryTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "sMS-startQueuedSMSDelivery",
      description: `Tells the ThingSpace Platform to start sending mobile-originated SMS messages through the EnhancedConnectivityService callback service. SMS messages from devices are queued until they are retrieved by... (truncated)`,
      inputSchema: await schemas.loadSchema("SMS", "StartQueuedSMSDelivery"),
    },
    handler: handleStartQueuedSMSDelivery,
  };
}

