/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  callbackActionResultSchema,
  type CallbackActionResult,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { connectivityCallbacksController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DeregisterCallbackMCPToolRequest {
  'aname': string,
  'sname': string,
}

const deregisterCallbackMCPToolRequestSchema = object({
  aname: ['aname', string()],
  sname: ['sname', string()],
});

async function handleDeregisterCallback(
  args: unknown | DeregisterCallbackMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, deregisterCallbackMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await connectivityCallbacksController.deregisterCallback(
      mappingResult.result['aname'],
      mappingResult.result['sname']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function connectivityCallbacksDeregisterCallbackTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "connectivityCallbacks-deregisterCallback",
      description: `Stops ThingSpace from sending callback messages for the specified account and service.`,
      inputSchema: await schemas.loadSchema("Connectivity Callbacks", "DeregisterCallback"),
    },
    handler: handleDeregisterCallback,
  };
}

