/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  callbackActionResultSchema,
  registerCallbackRequestSchema,
  type CallbackActionResult,
  type RegisterCallbackRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { connectivityCallbacksController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface RegisterCallbackMCPToolRequest {
  'aname': string,
  'body': RegisterCallbackRequest,
}

const registerCallbackMCPToolRequestSchema = object({
  aname: ['aname', string()],
  body: ['body', lazy(() => registerCallbackRequestSchema)],
});

async function handleRegisterCallback(
  args: unknown | RegisterCallbackMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, registerCallbackMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await connectivityCallbacksController.registerCallback(
      mappingResult.result['aname'],
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function connectivityCallbacksRegisterCallbackTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "connectivityCallbacks-registerCallback",
      description: `You are responsible for creating and running a listening process on your server at that URL.`,
      inputSchema: await schemas.loadSchema("Connectivity Callbacks", "RegisterCallback"),
    },
    handler: handleRegisterCallback,
  };
}

