/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  DeactivateDeviceListIds,
  deactivateDeviceListIdsSchema,
} from './containers/deactivateDeviceListIds';

export interface DeactivateDeviceList {
  ids?: DeactivateDeviceListIds[];
}

export const deactivateDeviceListSchema: Schema<DeactivateDeviceList> = object({
  ids: ['ids', optional(array(deactivateDeviceListIdsSchema))],
});
