/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema } from '../schema';
import {
  LabelsListDeviceIds,
  labelsListDeviceIdsSchema,
} from './containers/labelsListDeviceIds';

export interface LabelsList {
  deviceIds?: LabelsListDeviceIds[];
}

export const labelsListSchema: Schema<LabelsList> = object({
  deviceIds: ['deviceIds', optional(array(labelsListDeviceIdsSchema))],
});
