/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  carrierActivateRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type CarrierActivateRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ActivateServiceForDevicesMCPToolRequest {
  'body': CarrierActivateRequest,
}

const activateServiceForDevicesMCPToolRequestSchema = object({
  body: ['body', lazy(() => carrierActivateRequestSchema)],
});

async function handleActivateServiceForDevices(
  args: unknown | ActivateServiceForDevicesMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, activateServiceForDevicesMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.activateServiceForDevices(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementActivateServiceForDevicesTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-activateServiceForDevices",
      description: `If the devices do not already exist in the account, this API resource adds them before activation.`,
      inputSchema: await schemas.loadSchema("Device Management", "ActivateServiceForDevices"),
    },
    handler: handleActivateServiceForDevices,
  };
}

