/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  servicePlanUpdateRequestSchema,
  type DeviceManagementResult,
  type ServicePlanUpdateRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ChangeDevicesServicePlanMCPToolRequest {
  'body': ServicePlanUpdateRequest,
}

const changeDevicesServicePlanMCPToolRequestSchema = object({
  body: ['body', lazy(() => servicePlanUpdateRequestSchema)],
});

async function handleChangeDevicesServicePlan(
  args: unknown | ChangeDevicesServicePlanMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, changeDevicesServicePlanMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.changeDevicesServicePlan(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementChangeDevicesServicePlanTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-changeDevicesServicePlan",
      description: `Changes the service plan for one or more devices.`,
      inputSchema: await schemas.loadSchema("Device Management", "ChangeDevicesServicePlan"),
    },
    handler: handleChangeDevicesServicePlan,
  };
}

