/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceActivationRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type DeviceActivationRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface CheckDevicesAvailabilityForActivationMCPToolRequest {
  'body': DeviceActivationRequest,
}

const checkDevicesAvailabilityForActivationMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceActivationRequestSchema)],
});

async function handleCheckDevicesAvailabilityForActivation(
  args: unknown | CheckDevicesAvailabilityForActivationMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, checkDevicesAvailabilityForActivationMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.checkDevicesAvailabilityForActivation(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementCheckDevicesAvailabilityForActivationTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-checkDevicesAvailabilityForActivation",
      description: `Checks whether specified devices are registered by the manufacturer with the Verizon network and are available to be activated.`,
      inputSchema: await schemas.loadSchema("Device Management", "CheckDevicesAvailabilityForActivation"),
    },
    handler: handleCheckDevicesAvailabilityForActivation,
  };
}

