/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deleteDevicesRequestSchema,
  deleteDevicesResultSchema,
  type DeleteDevicesResult,
  type DeleteDevicesRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DeleteDeactivatedDevicesMCPToolRequest {
  'body': DeleteDevicesRequest,
}

const deleteDeactivatedDevicesMCPToolRequestSchema = object({
  body: ['body', lazy(() => deleteDevicesRequestSchema)],
});

async function handleDeleteDeactivatedDevices(
  args: unknown | DeleteDeactivatedDevicesMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, deleteDeactivatedDevicesMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.deleteDeactivatedDevices(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementDeleteDeactivatedDevicesTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-deleteDeactivatedDevices",
      description: `Use this API to remove unneeded devices from an account.`,
      inputSchema: await schemas.loadSchema("Device Management", "DeleteDeactivatedDevices"),
    },
    handler: handleDeleteDeactivatedDevices,
  };
}

