/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  checkOrderStatusRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type CheckOrderStatusRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface DeviceUploadStatusMCPToolRequest {
  'body': CheckOrderStatusRequest,
}

const deviceUploadStatusMCPToolRequestSchema = object({
  body: ['body', lazy(() => checkOrderStatusRequestSchema)],
});

async function handleDeviceUploadStatus(
  args: unknown | DeviceUploadStatusMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, deviceUploadStatusMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.deviceUploadStatus(mappingResult.result['body']);
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementDeviceUploadStatusTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-deviceUploadStatus",
      description: `Checks the status of an activation order and lists where the order is in the provisioning process.`,
      inputSchema: await schemas.loadSchema("Device Management", "DeviceUploadStatus"),
    },
    handler: handleDeviceUploadStatus,
  };
}

