/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  deviceSuspensionStatusRequestSchema,
  type DeviceManagementResult,
  type DeviceSuspensionStatusRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetDeviceServiceSuspensionStatusMCPToolRequest {
  'body': DeviceSuspensionStatusRequest,
}

const getDeviceServiceSuspensionStatusMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceSuspensionStatusRequestSchema)],
});

async function handleGetDeviceServiceSuspensionStatus(
  args: unknown | GetDeviceServiceSuspensionStatusMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, getDeviceServiceSuspensionStatusMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.getDeviceServiceSuspensionStatus(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementGetDeviceServiceSuspensionStatusTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-getDeviceServiceSuspensionStatus",
      description: `Returns DeviceSuspensionStatus callback messages containing the current device state and information on how many days a device has been suspended and can continue to be suspended.`,
      inputSchema: await schemas.loadSchema("Device Management", "GetDeviceServiceSuspensionStatus"),
    },
    handler: handleGetDeviceServiceSuspensionStatus,
  };
}

