/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceExtendedDiagnosticsRequestSchema,
  deviceExtendedDiagnosticsResultSchema,
  type DeviceExtendedDiagnosticsResult,
  type DeviceExtendedDiagnosticsRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface GetDeviceExtendedDiagnosticInformationMCPToolRequest {
  'body': DeviceExtendedDiagnosticsRequest,
}

const getDeviceExtendedDiagnosticInformationMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceExtendedDiagnosticsRequestSchema)],
});

async function handleGetDeviceExtendedDiagnosticInformation(
  args: unknown | GetDeviceExtendedDiagnosticInformationMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, getDeviceExtendedDiagnosticInformationMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.getDeviceExtendedDiagnosticInformation(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementGetDeviceExtendedDiagnosticInformationTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-getDeviceExtendedDiagnosticInformation",
      description: `Returns extended diagnostic information about a specified device, including connectivity, provisioning, billing and location status.`,
      inputSchema: await schemas.loadSchema("Device Management", "GetDeviceExtendedDiagnosticInformation"),
    },
    handler: handleGetDeviceExtendedDiagnosticInformation,
  };
}

