/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  devicePrlListRequestSchema,
  type DeviceManagementResult,
  type DevicePrlListRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListCurrentDevicesPRLVersionMCPToolRequest {
  'body': DevicePrlListRequest,
}

const listCurrentDevicesPRLVersionMCPToolRequestSchema = object({
  body: ['body', lazy(() => devicePrlListRequestSchema)],
});

async function handleListCurrentDevicesPRLVersion(
  args: unknown | ListCurrentDevicesPRLVersionMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listCurrentDevicesPRLVersionMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.listCurrentDevicesPRLVersion(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementListCurrentDevicesPRLVersionTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-listCurrentDevicesPRLVersion",
      description: `4G and GSM devices do not have a PRL.`,
      inputSchema: await schemas.loadSchema("Device Management", "ListCurrentDevicesPRLVersion"),
    },
    handler: handleListCurrentDevicesPRLVersion,
  };
}

