/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  accountDeviceListRequestSchema,
  accountDeviceListResultSchema,
  type AccountDeviceListResult,
  type AccountDeviceListRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListDevicesInformationMCPToolRequest {
  'body': AccountDeviceListRequest,
}

const listDevicesInformationMCPToolRequestSchema = object({
  body: ['body', lazy(() => accountDeviceListRequestSchema)],
});

async function handleListDevicesInformation(
  args: unknown | ListDevicesInformationMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listDevicesInformationMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.listDevicesInformation(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementListDevicesInformationTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-listDevicesInformation",
      description: `Returns information about a single device or information about all devices that match the given parameters. Returned information includes device provisioning state, service plan, MDN, MIN, and IP addr... (truncated)`,
      inputSchema: await schemas.loadSchema("Device Management", "ListDevicesInformation"),
    },
    handler: handleListDevicesInformation,
  };
}

