/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceUsageListRequestSchema,
  deviceUsageListResultSchema,
  type DeviceUsageListResult,
  type DeviceUsageListRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface ListDevicesUsageHistoryMCPToolRequest {
  'body': DeviceUsageListRequest,
}

const listDevicesUsageHistoryMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceUsageListRequestSchema)],
});

async function handleListDevicesUsageHistory(
  args: unknown | ListDevicesUsageHistoryMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, listDevicesUsageHistoryMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.listDevicesUsageHistory(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementListDevicesUsageHistoryTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-listDevicesUsageHistory",
      description: `Returns the network data usage history of a device during a specified time period.`,
      inputSchema: await schemas.loadSchema("Device Management", "ListDevicesUsageHistory"),
    },
    handler: handleListDevicesUsageHistory,
  };
}

