/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  moveDeviceRequestSchema,
  type DeviceManagementResult,
  type MoveDeviceRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface MoveDevicesWithinAccountsOfProfileMCPToolRequest {
  'body': MoveDeviceRequest,
}

const moveDevicesWithinAccountsOfProfileMCPToolRequestSchema = object({
  body: ['body', lazy(() => moveDeviceRequestSchema)],
});

async function handleMoveDevicesWithinAccountsOfProfile(
  args: unknown | MoveDevicesWithinAccountsOfProfileMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, moveDevicesWithinAccountsOfProfileMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.moveDevicesWithinAccountsOfProfile(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementMoveDevicesWithinAccountsOfProfileTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-moveDevicesWithinAccountsOfProfile",
      description: `Move active devices from one billing account to another within a customer profile.`,
      inputSchema: await schemas.loadSchema("Device Management", "MoveDevicesWithinAccountsOfProfile"),
    },
    handler: handleMoveDevicesWithinAccountsOfProfile,
  };
}

