/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  connectionHistoryResultSchema,
  deviceConnectionListRequestSchema,
  type ConnectionHistoryResult,
  type DeviceConnectionListRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface RetrieveDeviceConnectionHistoryMCPToolRequest {
  'body': DeviceConnectionListRequest,
}

const retrieveDeviceConnectionHistoryMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceConnectionListRequestSchema)],
});

async function handleRetrieveDeviceConnectionHistory(
  args: unknown | RetrieveDeviceConnectionHistoryMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, retrieveDeviceConnectionHistoryMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.retrieveDeviceConnectionHistory(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementRetrieveDeviceConnectionHistoryTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-retrieveDeviceConnectionHistory",
      description: `Each response includes a maximum of 500 records. To obtain more records, you can call the API multiple times, adjusting the earliest value each time to start where the previous request finished.`,
      inputSchema: await schemas.loadSchema("Device Management", "RetrieveDeviceConnectionHistory"),
    },
    handler: handleRetrieveDeviceConnectionHistory,
  };
}

