/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  customFieldsUpdateRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type CustomFieldsUpdateRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UpdateDevicesCustomFieldsMCPToolRequest {
  'body': CustomFieldsUpdateRequest,
}

const updateDevicesCustomFieldsMCPToolRequestSchema = object({
  body: ['body', lazy(() => customFieldsUpdateRequestSchema)],
});

async function handleUpdateDevicesCustomFields(
  args: unknown | UpdateDevicesCustomFieldsMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, updateDevicesCustomFieldsMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.updateDevicesCustomFields(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUpdateDevicesCustomFieldsTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-updateDevicesCustomFields",
      description: `Sends a CarrierService callback message for each device in the request when the custom fields have been changed, or if there was a problem and the change could not be completed.`,
      inputSchema: await schemas.loadSchema("Device Management", "UpdateDevicesCustomFields"),
    },
    handler: handleUpdateDevicesCustomFields,
  };
}

