/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  goToStateRequestSchema,
  type DeviceManagementResult,
  type GoToStateRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UpdateDevicesStateMCPToolRequest {
  'body': GoToStateRequest,
}

const updateDevicesStateMCPToolRequestSchema = object({
  body: ['body', lazy(() => goToStateRequestSchema)],
});

async function handleUpdateDevicesState(
  args: unknown | UpdateDevicesStateMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, updateDevicesStateMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.updateDevicesState(mappingResult.result['body']);
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUpdateDevicesStateTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-updateDevicesState",
      description: `Changes the provisioning state of one or more devices to a specified customer-defined service and state.`,
      inputSchema: await schemas.loadSchema("Device Management", "UpdateDevicesState"),
    },
    handler: handleUpdateDevicesState,
  };
}

