/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  changeDeviceIdRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type ChangeDeviceIdRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UpdateDeviceIdMCPToolRequest {
  'serviceType': string,
  'body': ChangeDeviceIdRequest,
}

const updateDeviceIdMCPToolRequestSchema = object({
  serviceType: ['serviceType', string()],
  body: ['body', lazy(() => changeDeviceIdRequestSchema)],
});

async function handleUpdateDeviceId(
  args: unknown | UpdateDeviceIdMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, updateDeviceIdMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.updateDeviceId(
      mappingResult.result['serviceType'],
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUpdateDeviceIdTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-updateDeviceId",
      description: `Changes the identifier of a 3G or 4G device to match hardware changes made for a line of service. Use this request to transfer the line of service and the MDN to new hardware, or to change the MDN.`,
      inputSchema: await schemas.loadSchema("Device Management", "UpdateDeviceId"),
    },
    handler: handleUpdateDeviceId,
  };
}

