/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceCostCenterRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type DeviceCostCenterRequest,
} from 'thingspace-connectivity-management-apilib';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UpdateDevicesCostCenterCodeMCPToolRequest {
  'body': DeviceCostCenterRequest,
}

const updateDevicesCostCenterCodeMCPToolRequestSchema = object({
  body: ['body', lazy(() => deviceCostCenterRequestSchema)],
});

async function handleUpdateDevicesCostCenterCode(
  args: unknown | UpdateDevicesCostCenterCodeMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, updateDevicesCostCenterCodeMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.updateDevicesCostCenterCode(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUpdateDevicesCostCenterCodeTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-updateDevicesCostCenterCode",
      description: `Changes or removes the CostCenterCode value or customer name and address (Primary Place of Use) for one or more devices.`,
      inputSchema: await schemas.loadSchema("Device Management", "UpdateDevicesCostCenterCode"),
    },
    handler: handleUpdateDevicesCostCenterCode,
  };
}

