/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  deviceManagementResultSchema,
  uploadsActivatesDeviceRequestSchema,
  type DeviceManagementResult,
  type UploadsActivatesDeviceRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UploadActivateDeviceMCPToolRequest {
  'body': UploadsActivatesDeviceRequest,
}

const uploadActivateDeviceMCPToolRequestSchema = object({
  body: ['body', lazy(() => uploadsActivatesDeviceRequestSchema)],
});

async function handleUploadActivateDevice(
  args: unknown | UploadActivateDeviceMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, uploadActivateDeviceMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.uploadActivateDevice(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUploadActivateDeviceTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-uploadActivateDevice",
      description: `Uploads and activates device identifiers and SKUs for new devices from OEMs to Verizon.`,
      inputSchema: await schemas.loadSchema("Device Management", "UploadActivateDevice"),
    },
    handler: handleUploadActivateDevice,
  };
}

