/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, string, validateAndMap } from '@apimatic/schema';
import { type CallToolResult } from '@modelcontextprotocol/sdk/types.js';
import {
  associateLabelRequestSchema,
  deviceManagementResultSchema,
  type DeviceManagementResult,
  type AssociateLabelRequest,
} from 'sdksio-verizon-apis-sdk';
import { schemas } from '../../schema.js';
import { deviceManagementController } from '../../sdk-client.js';
import { createErrorMessage, stringifyRawJson } from '../../utils.js';
import { type ToolDefinition } from '../index.js';


interface UsageSegmentationLabelAssociationMCPToolRequest {
  'body': AssociateLabelRequest,
}

const usageSegmentationLabelAssociationMCPToolRequestSchema = object({
  body: ['body', lazy(() => associateLabelRequestSchema)],
});

async function handleUsageSegmentationLabelAssociation(
  args: unknown | UsageSegmentationLabelAssociationMCPToolRequest
): Promise<CallToolResult> {
  const mappingResult = validateAndMap(args as any, usageSegmentationLabelAssociationMCPToolRequestSchema);
  if (mappingResult.errors) {
    return {
      content: mappingResult.errors.map(error => ({
        type: "text",
        text: stringifyRawJson(error)
      })),
      isError: true,
    };
  }

  try {
    const response = await deviceManagementController.usageSegmentationLabelAssociation(
      mappingResult.result['body']
    );
    return {
      content: [
        {
          type: "text",
          text: stringifyRawJson({
            statusCode: response.statusCode,
            responseHeaders: response.headers,
            result: response.body
          }),
        },
      ],
    };
  } catch (error) {
    return createErrorMessage(error);
  }
}

export async function deviceManagementUsageSegmentationLabelAssociationTool(): Promise<ToolDefinition> {
  return {
    tool: {
      name: "deviceManagement-usageSegmentationLabelAssociation",
      description: `Allows you to associate your own usage segmentation label with a device.`,
      inputSchema: await schemas.loadSchema("Device Management", "UsageSegmentationLabelAssociation"),
    },
    handler: handleUsageSegmentationLabelAssociation,
  };
}

