/**
 * ThingSpace Connectivity Management APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  type Tool,
  type CallToolResult,
} from '@modelcontextprotocol/sdk/types.js';
import { accountRequestsGetCurrentAsynchronousRequestStatusTool } from './accountRequests/getCurrentAsynchronousRequestStatus.js';
import { accountsGetAccountInformationTool } from './accounts/getAccountInformation.js';
import { accountsListAccountLeadsTool } from './accounts/listAccountLeads.js';
import { accountsListAccountStatesAndServicesTool } from './accounts/listAccountStatesAndServices.js';
import { connectivityCallbacksDeregisterCallbackTool } from './connectivityCallbacks/deregisterCallback.js';
import { connectivityCallbacksListRegisteredCallbacksTool } from './connectivityCallbacks/listRegisteredCallbacks.js';
import { connectivityCallbacksRegisterCallbackTool } from './connectivityCallbacks/registerCallback.js';
import { deviceDiagnosticsDeviceReachabilityStatusUsingPOSTTool } from './deviceDiagnostics/deviceReachabilityStatusUsingPOST.js';
import { deviceDiagnosticsRetrieveActiveMonitorsUsingPOSTTool } from './deviceDiagnostics/retrieveActiveMonitorsUsingPOST.js';
import { deviceGroupsCreateDeviceGroupTool } from './deviceGroups/createDeviceGroup.js';
import { deviceGroupsDeleteDeviceGroupTool } from './deviceGroups/deleteDeviceGroup.js';
import { deviceGroupsGetDeviceGroupInformationTool } from './deviceGroups/getDeviceGroupInformation.js';
import { deviceGroupsListDeviceGroupsTool } from './deviceGroups/listDeviceGroups.js';
import { deviceGroupsUpdateDeviceGroupTool } from './deviceGroups/updateDeviceGroup.js';
import { deviceManagementActivateServiceForDevicesTool } from './deviceManagement/activateServiceForDevices.js';
import { deviceManagementAddDevicesTool } from './deviceManagement/addDevices.js';
import { deviceManagementBilledUsageInfoTool } from './deviceManagement/billedUsageInfo.js';
import { deviceManagementChangeDevicesServicePlanTool } from './deviceManagement/changeDevicesServicePlan.js';
import { deviceManagementCheckDevicesAvailabilityForActivationTool } from './deviceManagement/checkDevicesAvailabilityForActivation.js';
import { deviceManagementDeactivateServiceForDevicesTool } from './deviceManagement/deactivateServiceForDevices.js';
import { deviceManagementDeleteDeactivatedDevicesTool } from './deviceManagement/deleteDeactivatedDevices.js';
import { deviceManagementDeviceUploadTool } from './deviceManagement/deviceUpload.js';
import { deviceManagementDeviceUploadStatusTool } from './deviceManagement/deviceUploadStatus.js';
import { deviceManagementGetDeviceExtendedDiagnosticInformationTool } from './deviceManagement/getDeviceExtendedDiagnosticInformation.js';
import { deviceManagementGetDeviceServiceSuspensionStatusTool } from './deviceManagement/getDeviceServiceSuspensionStatus.js';
import { deviceManagementListCurrentDevicesPRLVersionTool } from './deviceManagement/listCurrentDevicesPRLVersion.js';
import { deviceManagementListDevicesInformationTool } from './deviceManagement/listDevicesInformation.js';
import { deviceManagementListDevicesProvisioningHistoryTool } from './deviceManagement/listDevicesProvisioningHistory.js';
import { deviceManagementListDevicesUsageHistoryTool } from './deviceManagement/listDevicesUsageHistory.js';
import { deviceManagementListDevicesWithImeiIccidMismatchTool } from './deviceManagement/listDevicesWithImeiIccidMismatch.js';
import { deviceManagementMoveDevicesWithinAccountsOfProfileTool } from './deviceManagement/moveDevicesWithinAccountsOfProfile.js';
import { deviceManagementRestoreServiceForSuspendedDevicesTool } from './deviceManagement/restoreServiceForSuspendedDevices.js';
import { deviceManagementRetrieveAggregateDeviceUsageHistoryTool } from './deviceManagement/retrieveAggregateDeviceUsageHistory.js';
import { deviceManagementRetrieveDeviceConnectionHistoryTool } from './deviceManagement/retrieveDeviceConnectionHistory.js';
import { deviceManagementSuspendServiceForDevicesTool } from './deviceManagement/suspendServiceForDevices.js';
import { deviceManagementUpdateDeviceIdTool } from './deviceManagement/updateDeviceId.js';
import { deviceManagementUpdateDevicesContactInformationTool } from './deviceManagement/updateDevicesContactInformation.js';
import { deviceManagementUpdateDevicesCostCenterCodeTool } from './deviceManagement/updateDevicesCostCenterCode.js';
import { deviceManagementUpdateDevicesCustomFieldsTool } from './deviceManagement/updateDevicesCustomFields.js';
import { deviceManagementUpdateDevicesStateTool } from './deviceManagement/updateDevicesState.js';
import { deviceManagementUploadActivateDeviceTool } from './deviceManagement/uploadActivateDevice.js';
import { deviceManagementUsageSegmentationLabelAssociationTool } from './deviceManagement/usageSegmentationLabelAssociation.js';
import { deviceManagementUsageSegmentationLabelDeletionTool } from './deviceManagement/usageSegmentationLabelDeletion.js';
import { deviceMonitoringDeviceReachabilityTool } from './deviceMonitoring/deviceReachability.js';
import { deviceMonitoringStopDeviceReachabilityTool } from './deviceMonitoring/stopDeviceReachability.js';
import { deviceProfileManagementActivateDeviceThroughProfileTool } from './deviceProfileManagement/activateDeviceThroughProfile.js';
import { deviceProfileManagementProfileToActivateDeviceTool } from './deviceProfileManagement/profileToActivateDevice.js';
import { deviceProfileManagementProfileToDeactivateDeviceTool } from './deviceProfileManagement/profileToDeactivateDevice.js';
import { deviceProfileManagementProfileToSetFallbackAttributeTool } from './deviceProfileManagement/profileToSetFallbackAttribute.js';
import { eUICCDeviceProfileManagementDeleteLocalProfileTool } from './eUICCDeviceProfileManagement/deleteLocalProfile.js';
import { eUICCDeviceProfileManagementDisableLocalProfileTool } from './eUICCDeviceProfileManagement/disableLocalProfile.js';
import { eUICCDeviceProfileManagementDownloadLocalProfileToDisableTool } from './eUICCDeviceProfileManagement/downloadLocalProfileToDisable.js';
import { eUICCDeviceProfileManagementDownloadLocalProfileToEnableTool } from './eUICCDeviceProfileManagement/downloadLocalProfileToEnable.js';
import { eUICCDeviceProfileManagementEnableLocalProfileTool } from './eUICCDeviceProfileManagement/enableLocalProfile.js';
import { oAuthAuthorizationRequestTokenThingspaceOauthTool } from './oAuthAuthorization/requestTokenThingspaceOauth.js';
import { servicePlansListAccountServicePlansTool } from './servicePlans/listAccountServicePlans.js';
import { sessionManagementEndConnectivityManagementSessionTool } from './sessionManagement/endConnectivityManagementSession.js';
import { sessionManagementResetConnectivityManagementPasswordTool } from './sessionManagement/resetConnectivityManagementPassword.js';
import { sessionManagementStartConnectivityManagementSessionTool } from './sessionManagement/startConnectivityManagementSession.js';
import { sMSListDevicesSMSMessagesTool } from './sMS/listDevicesSMSMessages.js';
import { sMSSendSMSToDeviceTool } from './sMS/sendSMSToDevice.js';
import { sMSStartQueuedSMSDeliveryTool } from './sMS/startQueuedSMSDelivery.js';


export type ToolDefinition = {
  tool: Tool;
  handler: (arg: unknown) => Promise<CallToolResult>;
};

// Export all defined tools in an array
export async function getAllTools(): Promise<Record<string, ToolDefinition>> {
  const tools =   [
    deviceManagementActivateServiceForDevicesTool(),
    deviceManagementAddDevicesTool(),
    deviceManagementUpdateDevicesContactInformationTool(),
    deviceManagementUpdateDevicesCustomFieldsTool(),
    deviceManagementDeactivateServiceForDevicesTool(),
    deviceManagementDeleteDeactivatedDevicesTool(),
    deviceManagementListDevicesInformationTool(),
    deviceManagementListDevicesWithImeiIccidMismatchTool(),
    deviceManagementMoveDevicesWithinAccountsOfProfileTool(),
    deviceManagementUpdateDevicesStateTool(),
    deviceManagementChangeDevicesServicePlanTool(),
    deviceManagementSuspendServiceForDevicesTool(),
    deviceManagementRestoreServiceForSuspendedDevicesTool(),
    deviceManagementCheckDevicesAvailabilityForActivationTool(),
    deviceManagementRetrieveDeviceConnectionHistoryTool(),
    deviceManagementUpdateDevicesCostCenterCodeTool(),
    deviceManagementGetDeviceExtendedDiagnosticInformationTool(),
    deviceManagementListDevicesProvisioningHistoryTool(),
    deviceManagementListCurrentDevicesPRLVersionTool(),
    deviceManagementGetDeviceServiceSuspensionStatusTool(),
    deviceManagementListDevicesUsageHistoryTool(),
    deviceManagementRetrieveAggregateDeviceUsageHistoryTool(),
    deviceManagementUpdateDeviceIdTool(),
    deviceManagementDeviceUploadTool(),
    deviceManagementBilledUsageInfoTool(),
    deviceManagementUsageSegmentationLabelAssociationTool(),
    deviceManagementUsageSegmentationLabelDeletionTool(),
    deviceManagementUploadActivateDeviceTool(),
    deviceManagementDeviceUploadStatusTool(),
    accountsGetAccountInformationTool(),
    accountsListAccountStatesAndServicesTool(),
    accountsListAccountLeadsTool(),
    deviceGroupsCreateDeviceGroupTool(),
    deviceGroupsListDeviceGroupsTool(),
    deviceGroupsGetDeviceGroupInformationTool(),
    deviceGroupsUpdateDeviceGroupTool(),
    deviceGroupsDeleteDeviceGroupTool(),
    sMSSendSMSToDeviceTool(),
    sMSListDevicesSMSMessagesTool(),
    sMSStartQueuedSMSDeliveryTool(),
    sessionManagementStartConnectivityManagementSessionTool(),
    sessionManagementEndConnectivityManagementSessionTool(),
    sessionManagementResetConnectivityManagementPasswordTool(),
    connectivityCallbacksListRegisteredCallbacksTool(),
    connectivityCallbacksRegisterCallbackTool(),
    connectivityCallbacksDeregisterCallbackTool(),
    accountRequestsGetCurrentAsynchronousRequestStatusTool(),
    servicePlansListAccountServicePlansTool(),
    deviceDiagnosticsDeviceReachabilityStatusUsingPOSTTool(),
    deviceDiagnosticsRetrieveActiveMonitorsUsingPOSTTool(),
    deviceMonitoringDeviceReachabilityTool(),
    deviceMonitoringStopDeviceReachabilityTool(),
    deviceProfileManagementActivateDeviceThroughProfileTool(),
    deviceProfileManagementProfileToActivateDeviceTool(),
    deviceProfileManagementProfileToDeactivateDeviceTool(),
    deviceProfileManagementProfileToSetFallbackAttributeTool(),
    eUICCDeviceProfileManagementDownloadLocalProfileToEnableTool(),
    eUICCDeviceProfileManagementDownloadLocalProfileToDisableTool(),
    eUICCDeviceProfileManagementEnableLocalProfileTool(),
    eUICCDeviceProfileManagementDisableLocalProfileTool(),
    eUICCDeviceProfileManagementDeleteLocalProfileTool(),
    oAuthAuthorizationRequestTokenThingspaceOauthTool(),
  ];

  const resolvedTools = await Promise.all(tools);

  const toolMap: Record<string, ToolDefinition> = {};
  for (const toolDef of resolvedTools) {
    toolMap[toolDef.tool.name] = toolDef;
  }
  return toolMap;
}
